/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spor;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cico6
 */
public class MacGoster extends javax.swing.JFrame {
    
    baglanti veritabani = new baglanti();
    DefaultTableModel model = new DefaultTableModel();
    
    /**
     * Creates new form TakımGoster
     */
    public MacGoster() {
        initComponents();
        jTable1.setDefaultEditor(Object.class, null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_mac_goster = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_mac_skor1 = new javax.swing.JTextField();
        txt_mac_skor2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_mac_yer = new javax.swing.JTextField();
        txt_mac_tarih = new javax.swing.JTextField();
        txt_mac_spor = new javax.swing.JTextField();
        txt_mac_lig = new javax.swing.JTextField();
        btn_mac_ekle = new javax.swing.JButton();
        btn_mac_guncelle = new javax.swing.JButton();
        btn_mac_sil = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_mac_takim1ad = new javax.swing.JTextField();
        txt_mac_takim2ad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_mac_homeid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_mac_awayid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_mac_macid = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Maçlar");
        setLocation(new java.awt.Point(700, 320));

        btn_mac_goster.setBackground(new java.awt.Color(153, 153, 153));
        btn_mac_goster.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_mac_goster.setForeground(new java.awt.Color(255, 255, 255));
        btn_mac_goster.setText("Listele");
        btn_mac_goster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mac_gosterActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Ev Sahibi: ");

        jLabel3.setText("Skor 1: ");

        jLabel4.setText("Skor 2: ");

        txt_mac_skor1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_mac_skor1.setForeground(new java.awt.Color(153, 153, 153));
        txt_mac_skor1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));

        txt_mac_skor2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_mac_skor2.setForeground(new java.awt.Color(153, 153, 153));
        txt_mac_skor2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));

        jLabel5.setText("Yer: ");

        jLabel6.setText("Tarih: ");

        jLabel7.setText("Spor: ");

        jLabel8.setText("Lig: ");

        txt_mac_yer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_mac_yer.setForeground(new java.awt.Color(153, 153, 153));
        txt_mac_yer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));

        txt_mac_tarih.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_mac_tarih.setForeground(new java.awt.Color(153, 153, 153));
        txt_mac_tarih.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));

        txt_mac_spor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_mac_spor.setForeground(new java.awt.Color(153, 153, 153));
        txt_mac_spor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));

        txt_mac_lig.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_mac_lig.setForeground(new java.awt.Color(153, 153, 153));
        txt_mac_lig.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));

        btn_mac_ekle.setBackground(new java.awt.Color(51, 255, 0));
        btn_mac_ekle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_mac_ekle.setForeground(new java.awt.Color(204, 204, 0));
        btn_mac_ekle.setText("Ekle");
        btn_mac_ekle.setPreferredSize(new java.awt.Dimension(63, 17));
        btn_mac_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mac_ekleActionPerformed(evt);
            }
        });

        btn_mac_guncelle.setBackground(new java.awt.Color(51, 153, 255));
        btn_mac_guncelle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_mac_guncelle.setForeground(new java.awt.Color(204, 204, 0));
        btn_mac_guncelle.setText("Güncelle");
        btn_mac_guncelle.setMaximumSize(new java.awt.Dimension(340, 15));
        btn_mac_guncelle.setPreferredSize(new java.awt.Dimension(340, 17));
        btn_mac_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mac_guncelleActionPerformed(evt);
            }
        });

        btn_mac_sil.setBackground(new java.awt.Color(255, 51, 51));
        btn_mac_sil.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_mac_sil.setForeground(new java.awt.Color(204, 204, 0));
        btn_mac_sil.setText("Sil");
        btn_mac_sil.setPreferredSize(new java.awt.Dimension(340, 17));
        btn_mac_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mac_silActionPerformed(evt);
            }
        });

        jLabel2.setText("Misafir:");

        txt_mac_takim1ad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_mac_takim1ad.setForeground(new java.awt.Color(153, 153, 153));
        txt_mac_takim1ad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));

        txt_mac_takim2ad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_mac_takim2ad.setForeground(new java.awt.Color(153, 153, 153));
        txt_mac_takim2ad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));

        jLabel9.setText("Home ID:");

        txt_mac_homeid.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_mac_homeid.setForeground(new java.awt.Color(153, 153, 153));
        txt_mac_homeid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));

        jLabel10.setText("Away ID");

        txt_mac_awayid.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_mac_awayid.setForeground(new java.awt.Color(153, 153, 153));
        txt_mac_awayid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));

        jLabel11.setText("Maç ID");

        txt_mac_macid.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_mac_macid.setForeground(new java.awt.Color(153, 153, 153));
        txt_mac_macid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));

        jMenu1.setText("Dosya");

        jMenuItem2.setText("Ana Sayfa");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem1.setText("Takımlar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 209, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_mac_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mac_goster, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mac_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mac_sil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(201, 201, 201))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_mac_takim2ad, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(txt_mac_takim1ad)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_mac_skor1)
                            .addComponent(txt_mac_skor2)
                            .addComponent(txt_mac_homeid))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jLabel5)))
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_mac_macid)
                    .addComponent(txt_mac_awayid)
                    .addComponent(txt_mac_yer, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(txt_mac_tarih, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(txt_mac_spor, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(txt_mac_lig, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                .addGap(140, 140, 140))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_mac_takim1ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_mac_takim2ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_mac_skor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txt_mac_skor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_mac_homeid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_mac_yer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_mac_tarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_mac_spor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_mac_lig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_mac_awayid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_mac_macid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btn_mac_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_mac_goster, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btn_mac_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btn_mac_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mac_gosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mac_gosterActionPerformed
        // TODO add your handling code here:
         model.setRowCount(0);
        Object[] sutunlar ={"Maç ID","Home ID","Away ID","Ev Sahibi","Misafir","Skor 1","Skor 2","Yer","Tarih","Spor Adı","Lig Adı"};
        model.setColumnIdentifiers(sutunlar);
        ArrayList<TopluSporlar> maclar = new ArrayList<>();
        String gelen_spor = new String(txt_mac_spor.getText());
        String gelen_lig = new String(txt_mac_lig.getText());
       
       
        maclar = veritabani.macListele(gelen_spor,gelen_lig);
        if (maclar!=null) {
            for (TopluSporlar mac : maclar) {
                    
                Object[] satirlar = {mac.getMac_id(),mac.getTakim1id(),mac.getTakim2id(),mac.getTakim1ad(),mac.getTakim2ad(),mac.getSkor1(),mac.getSkor2(),mac.getYer(),
                mac.getTarih(),mac.getSporAdi(),mac.getLigAdi()
                };
                model.addRow(satirlar);
                        
            }
        }
        jTable1.setModel(model);
        if (gelen_spor.equals("")||gelen_lig.equals("")) {
            JOptionPane.showMessageDialog(null, "Spor adı veya Lig Adı boş geçilemez.","HATA",JOptionPane.WARNING_MESSAGE);
        }
         else if (model.getRowCount()==0) {
            JOptionPane.showMessageDialog(null, "Maç Bulunamadı.","HATA",JOptionPane.WARNING_MESSAGE);
        }
       
    }//GEN-LAST:event_btn_mac_gosterActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        AnaSayfa anasayfa = new AnaSayfa();
        this.setVisible(false);
        anasayfa.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btn_mac_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mac_ekleActionPerformed
        // TODO add your handling code here:
        TopluSporlar macEkle = new TopluSporlar(Integer.valueOf(txt_mac_homeid.getText()), Integer.valueOf(txt_mac_awayid.getText()), txt_mac_takim1ad.getText(), 
                txt_mac_takim2ad.getText(),
                Integer.valueOf(txt_mac_skor1.getText()), Integer.valueOf(txt_mac_skor2.getText()),
                txt_mac_yer.getText(), txt_mac_spor.getText(), txt_mac_lig.getText(), txt_mac_tarih.getText(), Integer.valueOf(txt_mac_macid.getText()));
        veritabani.macEkle(macEkle);
         btn_mac_gosterActionPerformed(evt);
    }//GEN-LAST:event_btn_mac_ekleActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        txt_mac_macid.setText((model.getValueAt(jTable1.getSelectedRow(), 0)).toString());
        txt_mac_homeid.setText((model.getValueAt(jTable1.getSelectedRow(), 1)).toString());
        txt_mac_awayid.setText((model.getValueAt(jTable1.getSelectedRow(), 2)).toString());
        txt_mac_takim1ad.setText((String) model.getValueAt(jTable1.getSelectedRow(), 3));
        txt_mac_takim2ad.setText((String) model.getValueAt(jTable1.getSelectedRow(), 4));
        txt_mac_skor1.setText((model.getValueAt(jTable1.getSelectedRow(), 5)).toString());
        txt_mac_skor2.setText((model.getValueAt(jTable1.getSelectedRow(), 6)).toString());
        txt_mac_yer.setText((String) model.getValueAt(jTable1.getSelectedRow(), 7));
        txt_mac_tarih.setText((String) model.getValueAt(jTable1.getSelectedRow(), 8));
        txt_mac_spor.setText((String) model.getValueAt(jTable1.getSelectedRow(), 9));
        txt_mac_lig.setText((String) model.getValueAt(jTable1.getSelectedRow(), 10));
        txt_mac_macid.setEditable(false);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_mac_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mac_guncelleActionPerformed
        // TODO add your handling code here:
         TopluSporlar mac = new TopluSporlar(Integer.valueOf(txt_mac_homeid.getText()),Integer.valueOf(txt_mac_awayid.getText()) , txt_mac_takim1ad.getText(), txt_mac_takim2ad.getText(), Integer.valueOf(txt_mac_skor1.getText()),Integer.valueOf(txt_mac_skor2.getText()) , txt_mac_yer.getText(), txt_mac_spor.getText(), txt_mac_lig.getText(), txt_mac_tarih.getText(), Integer.valueOf(txt_mac_macid.getText()));
         
         veritabani.macGuncelle(mac);
          btn_mac_gosterActionPerformed(evt);
    }//GEN-LAST:event_btn_mac_guncelleActionPerformed

    private void btn_mac_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mac_silActionPerformed
        // TODO add your handling code here:
        Object[] secimler = {"Evet", "Hayır"};
        int secim = JOptionPane.showOptionDialog(null, "Silmek İstiyor musunuz?","Sil",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,secimler,secimler[0]);
        if (secim == 0) {
             String id = txt_mac_macid.getText();
             veritabani.macSil(id);
             btn_mac_gosterActionPerformed(evt);
        }
       
    }//GEN-LAST:event_btn_mac_silActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        TakımGoster takım = new TakımGoster();
        this.setVisible(false);
        takım.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MacGoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MacGoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MacGoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MacGoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MacGoster().setVisible(true);
                
                
            }
        });
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_mac_ekle;
    private javax.swing.JButton btn_mac_goster;
    private javax.swing.JButton btn_mac_guncelle;
    private javax.swing.JButton btn_mac_sil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_mac_awayid;
    private javax.swing.JTextField txt_mac_homeid;
    private javax.swing.JTextField txt_mac_lig;
    private javax.swing.JTextField txt_mac_macid;
    private javax.swing.JTextField txt_mac_skor1;
    private javax.swing.JTextField txt_mac_skor2;
    private javax.swing.JTextField txt_mac_spor;
    private javax.swing.JTextField txt_mac_takim1ad;
    private javax.swing.JTextField txt_mac_takim2ad;
    private javax.swing.JTextField txt_mac_tarih;
    private javax.swing.JTextField txt_mac_yer;
    // End of variables declaration//GEN-END:variables
    
}
