/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spor;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cico6
 */
public class TakımGoster extends javax.swing.JFrame {
    
    baglanti veritabani = new baglanti();
    DefaultTableModel model= new DefaultTableModel();
    

    /**
     * Creates new form TakımGoster
     */
    public TakımGoster() {
        initComponents();
        jTable1.setDefaultEditor(Object.class, null);
        txt_takım_id.setEditable(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_takım_goster = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_takım_ad = new javax.swing.JTextField();
        txt_takım_yıl = new javax.swing.JTextField();
        txt_takım_spor = new javax.swing.JTextField();
        txt_takım_lig = new javax.swing.JTextField();
        btn_takım_ekle = new javax.swing.JButton();
        btn_takım_guncelle = new javax.swing.JButton();
        btn_takım_sil = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txt_takım_id = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Takımlar");
        setBackground(new java.awt.Color(204, 204, 0));
        setLocation(new java.awt.Point(750, 370));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_takım_goster.setBackground(new java.awt.Color(153, 153, 153));
        btn_takım_goster.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_takım_goster.setForeground(new java.awt.Color(255, 255, 255));
        btn_takım_goster.setText("Listele");
        btn_takım_goster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_takım_gosterActionPerformed(evt);
            }
        });
        getContentPane().add(btn_takım_goster, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 202, -1));

        jTable1.setBackground(new java.awt.Color(153, 0, 153));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTable1.setForeground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 375, 316));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("Takım Adı: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 97, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 0));
        jLabel2.setText("Kuruluş Yılı");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 135, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 0));
        jLabel3.setText("Spor Adı: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 173, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 0));
        jLabel4.setText("Lig Adı: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 211, -1, -1));

        txt_takım_ad.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_takım_ad.setForeground(new java.awt.Color(153, 153, 153));
        txt_takım_ad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));
        getContentPane().add(txt_takım_ad, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 94, 90, -1));

        txt_takım_yıl.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_takım_yıl.setForeground(new java.awt.Color(153, 153, 153));
        txt_takım_yıl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));
        getContentPane().add(txt_takım_yıl, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 132, 90, -1));

        txt_takım_spor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_takım_spor.setForeground(new java.awt.Color(153, 153, 153));
        txt_takım_spor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));
        getContentPane().add(txt_takım_spor, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 170, 90, -1));

        txt_takım_lig.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_takım_lig.setForeground(new java.awt.Color(153, 153, 153));
        txt_takım_lig.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));
        getContentPane().add(txt_takım_lig, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 208, 90, -1));

        btn_takım_ekle.setBackground(new java.awt.Color(51, 255, 0));
        btn_takım_ekle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_takım_ekle.setForeground(new java.awt.Color(204, 204, 0));
        btn_takım_ekle.setText("Ekle");
        btn_takım_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_takım_ekleActionPerformed(evt);
            }
        });
        getContentPane().add(btn_takım_ekle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 246, 202, -1));

        btn_takım_guncelle.setBackground(new java.awt.Color(51, 153, 255));
        btn_takım_guncelle.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_takım_guncelle.setForeground(new java.awt.Color(204, 204, 0));
        btn_takım_guncelle.setText("Güncelle");
        btn_takım_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_takım_guncelleActionPerformed(evt);
            }
        });
        getContentPane().add(btn_takım_guncelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 287, 202, -1));

        btn_takım_sil.setBackground(new java.awt.Color(255, 51, 51));
        btn_takım_sil.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_takım_sil.setForeground(new java.awt.Color(204, 204, 0));
        btn_takım_sil.setText("Sil");
        btn_takım_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_takım_silActionPerformed(evt);
            }
        });
        getContentPane().add(btn_takım_sil, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 328, 202, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 149, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 0));
        jLabel5.setText("Takım ID:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 59, -1, -1));

        txt_takım_id.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_takım_id.setForeground(new java.awt.Color(153, 153, 153));
        txt_takım_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));
        getContentPane().add(txt_takım_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 56, 90, -1));

        jMenu1.setText("Dosya");

        jMenuItem2.setText("Ana Sayfa");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem1.setText("Maçlar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_takım_gosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_takım_gosterActionPerformed
        // TAKIM LİSTELE
        model.setRowCount(0);
        Object[] sutunlar ={"Takım ID","Takım Adı","Kuruluş Yılı","Spor Adı","Lig Adı"};
        model.setColumnIdentifiers(sutunlar);
        ArrayList<Takım> tk1 = new ArrayList<>();
        String gelen_spor = new String(txt_takım_spor.getText());
        String gelen_lig = new String(txt_takım_lig.getText());
       
       
        tk1 = veritabani.takımListele(gelen_spor,gelen_lig);
        if (tk1!=null) {
            for (Takım takım : tk1) {
                    
                Object[] satirlar = {takım.getTakim_id(),takım.getTakimAdi(),takım.getKurulusYili(),takım.getSporAdi(),takım.getLigAdi()};
                model.addRow(satirlar);
                        
            }
        }
        jTable1.setModel(model);
        if (gelen_spor.equals("")||gelen_lig.equals("")) {
            JOptionPane.showMessageDialog(null, "Spor adı veya Lig Adı boş geçilemez.","HATA",JOptionPane.WARNING_MESSAGE);
        }
         else if (model.getRowCount()==0) {
            JOptionPane.showMessageDialog(null, "Takım Bulunamadı.","HATA",JOptionPane.WARNING_MESSAGE);
        }
       
    }//GEN-LAST:event_btn_takım_gosterActionPerformed

    private void btn_takım_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_takım_ekleActionPerformed
        // TAKIM EKLE
        Takım tkmEkle = new Takım(txt_takım_ad.getText(), Integer.valueOf(txt_takım_yıl.getText()), txt_takım_spor.getText(), txt_takım_lig.getText());
        veritabani.ekle(tkmEkle);
         btn_takım_gosterActionPerformed(evt);
        
        
        
    }//GEN-LAST:event_btn_takım_ekleActionPerformed

    private void btn_takım_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_takım_guncelleActionPerformed
        // TAKIM GÜNCELLE
         Takım tkmGuncelle = new Takım(txt_takım_ad.getText(), Integer.valueOf(txt_takım_yıl.getText()), txt_takım_spor.getText(), txt_takım_lig.getText(),Integer.valueOf(txt_takım_id.getText()));
         veritabani.guncelle(tkmGuncelle);
          btn_takım_gosterActionPerformed(evt);
         
    }//GEN-LAST:event_btn_takım_guncelleActionPerformed

    private void btn_takım_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_takım_silActionPerformed
        // TODO add your handling code here:
        
        Object[] secimler = {"Evet", "Hayır"};
        int secim = JOptionPane.showOptionDialog(null, "Silmek İstiyor musunuz?","Sil",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,secimler,secimler[0]);
        if (secim == 0) {
              String id = txt_takım_id.getText();
        veritabani.sil(id);
        btn_takım_gosterActionPerformed(evt);
        }
        
        
       
    }//GEN-LAST:event_btn_takım_silActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        AnaSayfa anasayfa = new AnaSayfa();
        this.setVisible(false);
        anasayfa.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // SEÇİLEN SATIRI TEXTBOXA YAZDIR
        txt_takım_id.setText((model.getValueAt(jTable1.getSelectedRow(), 0)).toString());
        txt_takım_ad.setText((String) model.getValueAt(jTable1.getSelectedRow(), 1));
        txt_takım_yıl.setText((model.getValueAt(jTable1.getSelectedRow(), 2)).toString());
        txt_takım_spor.setText((String) model.getValueAt(jTable1.getSelectedRow(), 3));
        txt_takım_lig.setText((String) model.getValueAt(jTable1.getSelectedRow(), 4));
        txt_takım_id.setEditable(false);
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        MacGoster mac = new MacGoster();
        this.setVisible(false);
        mac.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TakımGoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TakımGoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TakımGoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TakımGoster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TakımGoster().setVisible(true);
                
                
            }
        });
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_takım_ekle;
    private javax.swing.JButton btn_takım_goster;
    private javax.swing.JButton btn_takım_guncelle;
    private javax.swing.JButton btn_takım_sil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_takım_ad;
    private javax.swing.JTextField txt_takım_id;
    private javax.swing.JTextField txt_takım_lig;
    private javax.swing.JTextField txt_takım_spor;
    private javax.swing.JTextField txt_takım_yıl;
    // End of variables declaration//GEN-END:variables
    
}
